export const questionCategories = [
  {
    id: 'preferences',
    label: 'Preferences',
    pairs: [
      { regular: 'Would you rather spend a day at the beach or in the mountains?', impostor: 'Would you rather spend a day in the city or in the countryside?' },
      { regular: 'Do you prefer coffee or tea in the morning?', impostor: 'Do you prefer juice or water in the morning?' },
      { regular: 'Would you rather watch a movie at home or at the theater?', impostor: 'Would you rather listen to music at home or at a concert?' },
      { regular: 'Do you prefer summer or winter?', impostor: 'Do you prefer spring or autumn?' },
      { regular: 'Would you rather eat pizza or burgers?', impostor: 'Would you rather eat tacos or sandwiches?' },
      { regular: 'Do you prefer cats or dogs as pets?', impostor: 'Do you prefer fish or birds as pets?' },
      { regular: 'Would you rather travel by plane or by train?', impostor: 'Would you rather travel by car or by boat?' },
      { regular: 'Do you prefer action movies or romantic movies?', impostor: 'Do you prefer horror movies or comedies?' },
    ],
  },
  {
    id: 'hypothetical',
    label: 'Hypothetical',
    pairs: [
      { regular: 'If you could have any superpower, what would it be?', impostor: 'If you could have any magical item, what would it be?' },
      { regular: 'If you could live in any country, where would you go?', impostor: 'If you could live in any city, where would you go?' },
      { regular: 'If you could meet any historical figure, who would it be?', impostor: 'If you could meet any fictional character, who would it be?' },
      { regular: 'If you could only eat one food for the rest of your life, what would it be?', impostor: 'If you could only drink one beverage for the rest of your life, what would it be?' },
      { regular: 'If you won a million dollars, what\'s the first thing you\'d buy?', impostor: 'If you won a free vacation, where would you go first?' },
      { regular: 'If you could go back in time, what year would you visit?', impostor: 'If you could travel to the future, what year would you visit?' },
      { regular: 'If you could instantly master any skill, what would it be?', impostor: 'If you could instantly learn any language, which would it be?' },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    pairs: [
      { regular: 'What\'s your favorite childhood memory?', impostor: 'What\'s your favorite memory from your teenage years?' },
      { regular: 'What\'s the most adventurous thing you\'ve ever done?', impostor: 'What\'s the most spontaneous thing you\'ve ever done?' },
      { regular: 'What\'s something you\'re really proud of accomplishing?', impostor: 'What\'s something you worked really hard to learn?' },
      { regular: 'What\'s your go-to comfort food when you\'re upset?', impostor: 'What\'s your go-to activity when you need to relax?' },
      { regular: 'What\'s a hobby you\'ve always wanted to try?', impostor: 'What\'s a place you\'ve always wanted to visit?' },
      { regular: 'What\'s the best piece of advice you\'ve ever received?', impostor: 'What\'s the best lesson life has taught you?' },
      { regular: 'What\'s something small that always makes you happy?', impostor: 'What\'s something simple that always makes you smile?' },
    ],
  },
  {
    id: 'funny',
    label: 'Funny',
    pairs: [
      { regular: 'What\'s the most embarrassing thing that happened to you at school?', impostor: 'What\'s the most embarrassing thing that happened to you at work?' },
      { regular: 'What\'s the weirdest food combination you actually enjoy?', impostor: 'What\'s the strangest habit you have that others find odd?' },
      { regular: 'If you were a vegetable, which one would you be and why?', impostor: 'If you were a fruit, which one would you be and why?' },
      { regular: 'What\'s the funniest excuse you\'ve made to get out of something?', impostor: 'What\'s the funniest lie you\'ve told that actually worked?' },
      { regular: 'What\'s a weird talent you have that most people don\'t know about?', impostor: 'What\'s a strange skill you accidentally picked up?' },
      { regular: 'If your life was a TV show, what genre would it be?', impostor: 'If your life was a movie, what genre would it be?' },
    ],
  },
  {
    id: 'deep',
    label: 'Deep Questions',
    pairs: [
      { regular: 'What do you think is the meaning of life?', impostor: 'What do you think is the purpose of existence?' },
      { regular: 'What\'s one thing you\'d change about the world if you could?', impostor: 'What\'s one thing you\'d change about society if you could?' },
      { regular: 'Do you believe in fate or free will?', impostor: 'Do you believe in luck or hard work?' },
      { regular: 'What\'s something you believe that most people disagree with?', impostor: 'What\'s an unpopular opinion you strongly hold?' },
      { regular: 'What legacy do you want to leave behind?', impostor: 'How do you want to be remembered after you\'re gone?' },
      { regular: 'What\'s your biggest fear in life?', impostor: 'What\'s your biggest regret so far in life?' },
    ],
  },
];
